version: 0.{build}
nuget:
  project_feed: true
before_build:
- cmd: nuget restore source\tfm.sln
build:
  project: source\tfm.sln
  verbosity: minimal

artifacts:
- path: source\bin\debug
  name: tfm-pre0.{build}
  type: zip
  
deploy:
  provider: FTP
  protocol: sftp
  host: vps.fayre.me
  username: bvipilots
  password:
    secure: gsDOGtodux/gAPPDTybI5w=
  folder: /home/bvipilots/public_html/tfm-snapshots

notifications:
- provider: Email
  to:
  - jfayre@gmail.com
  subject: TFM build
  on_build_success: true
  on_build_failure: true