version: 0.{build}
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  project: source\tfm.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - jfayre@gmail.com
  subject: TFM build
  on_build_success: true
  on_build_failure: true