using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace tfm.Settings_panels
{
    public static class PMDG737VerbosityItems
    {
        public static List<PMDGVerbositySetting> pMDGVerbositySettings
        {
            get => new List<PMDGVerbositySetting>()
            {
                                // --panel: Aft OverheadPanel
                // --section: ADIRU
                                new PMDGVerbositySetting { Name = "IRS Display Selector", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_DisplaySelector" },
                new PMDGVerbositySetting { Name = "IRS Display switch", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_SysDisplay_r" },
                new PMDGVerbositySetting { Name = "IRS GPS light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunGPS" },
                new PMDGVerbositySetting { Name = "Left IRS light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunALIGN_L" },
                new PMDGVerbositySetting { Name = "Right IRS light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunALIGN_R" },
                new PMDGVerbositySetting { Name = "Left IRS DC light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunON_DC_L" },
                new PMDGVerbositySetting { Name = "Right IRS DC light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunON_DC_R" },
                new PMDGVerbositySetting { Name = "Left IRS fault light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunFAULT_L" },
                new PMDGVerbositySetting { Name = "Right IRS fault light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunFAULT_R" },
                new PMDGVerbositySetting { Name = "Left IRS DC failure light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunDC_FAIL_L" },
                new PMDGVerbositySetting { Name = "Right IRS DC failure light", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_annunDC_FAIL_R" },
                new PMDGVerbositySetting { Name = "Left IRS mode selector", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_ModeSelector_L" },
                new PMDGVerbositySetting { Name = "Right IRS mode selector", PanelName = "Aft Overhead", PanelSection = "ADIRU", SettingKey = "IRS_ModeSelector_R" },
                
                // --section: PSEU
                    new PMDGVerbositySetting { Name = "PSEU warning light",  PanelName = "Aft Overhead", PanelSection = "PSEU", SettingKey = "WARN_annunPSEU" },

                // --section: Service interphone
new PMDGVerbositySetting {Name = "Service interphone", PanelName = "Aft Overhead", PanelSection = "Service interphone", SettingKey = "COMM_ServiceInterphoneSw" },

// --section: lights
new PMDGVerbositySetting { Name = "Dome lights", PanelName = "Aft Overhead", PanelSection = "Lights", SettingKey = "LTS_DomeWhiteSw" },

// --section: Engines
new PMDGVerbositySetting { Name = "Engine #1 EEC", PanelName = "Aft Overhead", PanelSection = "Engines", SettingKey = "ENG_EECSwitch_1" },
new PMDGVerbositySetting { Name = "Engine #2 EEC", PanelName = "Aft Overhead", PanelSection = "Engines", SettingKey = "ENG_EECSwitch_2" },
new PMDGVerbositySetting { Name = "Engine #1 reverser light", PanelName = "Aft Overhead", PanelSection = "Engines", SettingKey = "ENG_annunREVERSER_1" },
new PMDGVerbositySetting { Name = "Engine #2 reverser light", PanelName = "Aft Overhead", PanelSection = "Engines", SettingKey = "ENG_annunREVERSER_2" },
new PMDGVerbositySetting { Name = "Engine #1 control light", PanelName = "Aft Overhead", PanelSection = "Engines", SettingKey = "ENG_annunENGINE_CONTROL_1" },
new PMDGVerbositySetting { Name = "Engine #2 control light", PanelName = "Aft Overhead", PanelSection = "Engines", SettingKey = "ENG_annunENGINE_CONTROL_2" },
new PMDGVerbositySetting { Name = "Engine #1 alternate control light", PanelName = "Aft Overhead", PanelSection = "Engines", SettingKey = "ENG_annunALTN_1" },
new PMDGVerbositySetting { Name = "Engine #2 alternate control light", PanelName = "Aft Overhead", PanelSection = "Engines", SettingKey = "ENG_annunALTN_2" },

// --section: Oxygen
new PMDGVerbositySetting { Name = "Oxygen level", PanelName = "Aft Overhead", PanelSection = "Oxygen", SettingKey = "OXY_Needle" },
new PMDGVerbositySetting { Name = "Oxygen", PanelName = "Aft Overhead", PanelSection = "Oxygen", SettingKey = "OXY_Needle" },
new PMDGVerbositySetting { Name = "Passenger oxygen light", PanelName = "Aft Overhead", PanelSection = "Oxygen", SettingKey = "OXY_annunPASS_OXY_ON" },

// --section: Gear
new PMDGVerbositySetting { Name = "Nose gear light", PanelName = "Aft Overhead", PanelSection = "Gear", SettingKey = "GEAR_annunOvhdNOSE" },
new PMDGVerbositySetting { Name = "Left gear light", PanelName = "Aft Overhead", PanelSection = "Gear", SettingKey = "GEAR_annunOvhdLEFT" },
new PMDGVerbositySetting { Name = "Right gear light", PanelName = "Aft Overhead", PanelSection = "Gear", SettingKey = "GEAR_annunOvhdRIGHT" },

// --section: Flight recorder
new PMDGVerbositySetting { Name = "Flight recorder", PanelName = "Aft Overhead", PanelSection = "Flight recorder", SettingKey = "FLTREC_SwNormal" },
new PMDGVerbositySetting { Name = "Flight recorder light", PanelName = "Aft Overhead", PanelSection = "Flight recorder", SettingKey = "FLTREC_annunOFF" },

// --panel: Forward Overhead
// --section: Flight controls
new PMDGVerbositySetting { Name = "Flight control [A]", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_FltControl_Sw_1" },
                new PMDGVerbositySetting { Name = "Flight control [B]", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_FltControl_Sw_2" },
new PMDGVerbositySetting { Name = "Spoilers A", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_Spoiler_Sw_1" },
new PMDGVerbositySetting { Name = "Spoilers B", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_Spoiler_Sw_2" },
new PMDGVerbositySetting { Name = "Yaw damper", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_YawDamper_Sw" },
new PMDGVerbositySetting { Name = "Alternate flaps [armed]", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_AltnFlaps_Sw_ARM" },
new PMDGVerbositySetting{Name = "Alternate flaps", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_AltnFlaps_Control_Sw" },
new PMDGVerbositySetting{Name = "Flight control [A] low pressure light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunFC_LOW_PRESSURE_1" },
new PMDGVerbositySetting{Name = "Flight control [B] low pressure light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunFC_LOW_PRESSURE_2" },
new PMDGVerbositySetting{ Name = "Yaw damper light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunYAW_DAMPER" },
new PMDGVerbositySetting { Name = "Flight controls low quantity light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunLOW_QUANTITY" },
new PMDGVerbositySetting { Name = "Flight controls low pressure light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunLOW_PRESSURE" },
new PMDGVerbositySetting { Name = "Flight controls standby/rudder light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunLOW_STBY_RUD_ON" },
new PMDGVerbositySetting { Name = "Feel diff pressure light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunFEEL_DIFF_PRESS" },
new PMDGVerbositySetting { Name = "Speed trim failed light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunSPEED_TRIM_FAIL" },
new PMDGVerbositySetting { Name = "Mach trim failed light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunMACH_TRIM_FAIL" },
new PMDGVerbositySetting { Name = "Auto slat failed light", PanelName = "Forward Overhead", PanelSection = "Flight controls", SettingKey = "FCTL_annunAUTO_SLAT_FAIL" },

// ---section: Navigation/Displays
new PMDGVerbositySetting { Name = "VHF navigation selector", PanelName = "Forward Overhead", PanelSection = "Navigation/Displays", SettingKey = "NAVDIS_VHFNavSelector" },
new PMDGVerbositySetting { Name = "IRS selector", PanelName = "Forward Overhead", PanelSection = "Navigation/Displays", SettingKey = "NAVDIS_IRSSelector" },
new PMDGVerbositySetting { Name = "FMC selector", PanelName = "Forward Overhead", PanelSection = "Navigation/Displays", SettingKey = "NAVDIS_FMCSelector" },
new PMDGVerbositySetting { Name = "Source selector", PanelName = "Forward Overhead", PanelSection = "Navigation/Displays", SettingKey = "NAVDIS_SourceSelector" },
new PMDGVerbositySetting {Name = "Control pane selector", PanelName = "Forward Overhead", PanelSection = "Navigation/Displays", SettingKey = "NAVDIS_ControlPaneSelector" },

// ---section: fuel
new PMDGVerbositySetting { Name = "Fuel temprature", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_FuelTempNeedle" },
new PMDGVerbositySetting { Name = "Crossfeed", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_CrossFeedSw" },
new PMDGVerbositySetting { Name = "Left FWD fuel pump ", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_PumpFwdSw_L" },
new PMDGVerbositySetting { Name = "Right FWD fuel pump", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_PumpFwdSw_R" },
new PMDGVerbositySetting { Name = "Left AFT fuel pump", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_PumpAftSw_L" },
new PMDGVerbositySetting { Name = "Right AFT fuel pump", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_PumpAftSw_R" },
new PMDGVerbositySetting { Name = "Left center fuel pump", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_PumpCtrSw_L" },
new PMDGVerbositySetting { Name = "Right center fuel pump", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_PumpCtrSw_R" },
new PMDGVerbositySetting { Name = "AFT A: aux fuel", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_AuxAft_A" },
new PMDGVerbositySetting { Name = "AFT B: aux fuel", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_AuxAft_B" },
new PMDGVerbositySetting { Name = "FWD A: aux fuel", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_AuxFwd_A" },
// new PMDGVerbositySetting { Name = "FWD B: aux fuel", PanelName = "Forward Overhead", PanelSection = "Fuel"" },
new PMDGVerbositySetting { Name = "FWD fuel bleed", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_FWDBleed" },
new PMDGVerbositySetting { Name = "AFT fuel bleed", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_AFTBleed" },
new PMDGVerbositySetting { Name = "Ground fuel transfer", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_GNDXfr" },
new PMDGVerbositySetting { Name = "Engine #1 fuel valve light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunENG_VALVE_CLOSED_1" },
new PMDGVerbositySetting { Name = "Engine #2 fuel valve light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunENG_VALVE_CLOSED_2" },
new PMDGVerbositySetting { Name = "Engine #1 spar valve light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunSPAR_VALVE_CLOSED_1" },
new PMDGVerbositySetting { Name = "Engine #2 spar valve light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunSPAR_VALVE_CLOSED_2" },
new PMDGVerbositySetting { Name = "Engine #1 fuel filter bypass light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunFILTER_BYPASS_1" },
new PMDGVerbositySetting { Name = "Engine #2 fuel filter bypass light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunFILTER_BYPASS_2" },
new PMDGVerbositySetting { Name = "Crossfeed valve light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunXFEED_VALVE_OPEN" },
new PMDGVerbositySetting { Name = "Engine #1 AFT low pressure light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunLOWPRESS_Aft_1" },
new PMDGVerbositySetting { Name = "Engine #2 AFT low pressure light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunLOWPRESS_Aft_2" },
new PMDGVerbositySetting { Name = "Engine #1 FWD low pressure light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunLOWPRESS_Fwd_1" },
new PMDGVerbositySetting { Name = "Engine #2 FWD low pressure light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunLOWPRESS_Fwd_2" },
new PMDGVerbositySetting { Name = "Engine #1 center low pressure light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunLOWPRESS_Ctr_1" },
new PMDGVerbositySetting { Name = "Engine #2 center low pressure light", PanelName = "Forward Overhead", PanelSection = "Fuel", SettingKey = "FUEL_annunLOWPRESS_Ctr_2" },

// --section: Electrical
new PMDGVerbositySetting { Name = "Battery discharge light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunBAT_DISCHARGE" },
new PMDGVerbositySetting { Name = "TR unit light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunTR_UNIT" },
new PMDGVerbositySetting{ Name = "Elec light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunELEC" },
new PMDGVerbositySetting{ Name = "DC meter selector", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_DCMeterSelector" },
new PMDGVerbositySetting { Name = "AC meter selector", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_ACMeterSelector" },
new PMDGVerbositySetting { Name = "Battery", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_BatSelector" },
new PMDGVerbositySetting { Name = "Cabin utility", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_CabUtilSw" },
new PMDGVerbositySetting { Name = "Passenger seats", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_IFEPassSeatSw" },
new PMDGVerbositySetting { Name = "Drive #1 light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunDRIVE_1" },
new PMDGVerbositySetting { Name = "Drive #2 light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunDRIVE_2" },
new PMDGVerbositySetting { Name = "Standby power light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunSTANDBY_POWER_OFF" },
new PMDGVerbositySetting { Name = "IDG #1 disconnect", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_IDGDisconnectSw_1" },
new PMDGVerbositySetting { Name = "IDG #2 disconnect", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_IDGDisconnectSw_2" },
new PMDGVerbositySetting { Name = "Standby power selector", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_StandbyPowerSelector" },
new PMDGVerbositySetting { Name = "Ground power light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunGRD_POWER_AVAILABLE" },
new PMDGVerbositySetting { Name = "Ground power", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_GrdPwrSw" },
new PMDGVerbositySetting { Name = "Bus transfer", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_BusTransSw_AUTO" },
new PMDGVerbositySetting { Name = "Generator #1", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_GenSw_1" },
new PMDGVerbositySetting { Name = "Generator #2", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_GenSw_2" },
new PMDGVerbositySetting { Name = "APU generator #1", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_APUGenSw_1" },
new PMDGVerbositySetting { Name = "APU generator #2", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_APUGenSw_2" },
new PMDGVerbositySetting { Name = "Transfer bus #1 light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunTRANSFER_BUS_OFF_1" },
new PMDGVerbositySetting { Name = "Transfer bus #2 light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunTRANSFER_BUS_OFF_2" },
new PMDGVerbositySetting { Name = "DC source light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunSOURCE_OFF_1" },
new PMDGVerbositySetting { Name = "AC source light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunSOURCE_OFF_2" },
new PMDGVerbositySetting { Name = "Generator #1 bus light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunGEN_BUS_OFF_1" },
new PMDGVerbositySetting { Name = "Generator #2 bus light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunGEN_BUS_OFF_2" },
new PMDGVerbositySetting { Name = "APU generator bus light", PanelName = "Forward Overhead", PanelSection = "Electrical", SettingKey = "ELEC_annunAPU_GEN_OFF_BUS" },

// --section: APU
new PMDGVerbositySetting { Name = "APU EGT needle", PanelName = "Forward Overhead", PanelSection = "APU", SettingKey = "APU_EGTNeedle" },
new PMDGVerbositySetting { Name = "APU maint light", PanelName = "Forward Overhead", PanelSection = "APU", SettingKey = "APU_annunMAINT" },
new PMDGVerbositySetting { Name = "APU low oil pressure light", PanelName = "Forward Overhead", PanelSection = "APU", SettingKey = "APU_annunLOW_OIL_PRESSURE" },
new PMDGVerbositySetting { Name = "APU fault light", PanelName = "Forward Overhead", PanelSection = "APU", SettingKey = "APU_annunFAULT" },
new PMDGVerbositySetting { Name = "APU overspeed light", PanelName = "Forward Overhead", PanelSection = "APU", SettingKey = "APU_annunOVERSPEED" },

// --section: Wipers
new PMDGVerbositySetting { Name = "Left wipers", PanelName = "Forward Overhead", PanelSection = "Wipers", SettingKey = "OH_WiperLSelector" },
new PMDGVerbositySetting { Name = "Right wipers", PanelName = "Forward Overhead", PanelSection = "Wipers", SettingKey = "OH_WiperRSelector" },

// --panel: Center Overhead
// -- section: Main

new PMDGVerbositySetting { Name = "Circutt breaker knob", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "LTS_CircuitBreakerKnob" },
new PMDGVerbositySetting { Name = "Overhead panel knob", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "LTS_OvereadPanelKnob" },
new PMDGVerbositySetting { Name = "Emergency exit lights", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "LTS_EmerExitSelector" },
new PMDGVerbositySetting { Name = "Equipment cooling supply", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "AIR_EquipCoolingSupplyNORM" },
new PMDGVerbositySetting { Name = "Equipment cooling exhaust", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "AIR_EquipCoolingExhaustNORM" },
new PMDGVerbositySetting { Name = "Chimes", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "COMM_NoSmokingSelector" },
new PMDGVerbositySetting { Name = "Seatbelt selector", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "COMM_FastenBeltsSelector" },
new PMDGVerbositySetting { Name = "Emergency exit N/armed light", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "LTS_annunEmerNOT_ARMED" },
new PMDGVerbositySetting { Name = "Equipment cooling supply light", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "AIR_annunEquipCoolingSupplyOFF" },
new PMDGVerbositySetting { Name = "Equipment cooling exhaust light", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "AIR_annunEquipCoolingExhaustOFF" },
new PMDGVerbositySetting { Name = "Call light", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "COMM_annunCALL" },
new PMDGVerbositySetting { Name = "PA in use light", PanelName = "Center Overhead", PanelSection = "Main", SettingKey = "COMM_annunPA_IN_USE" },

// Anti-ice
new PMDGVerbositySetting { Name = "Left side window heat", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_WindowHeatSw1" },
new PMDGVerbositySetting { Name = "Left forward window heat", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_WindowHeatSw2" },
new PMDGVerbositySetting { Name = "Right forward window heat", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_WindowHeatSw3" },
new PMDGVerbositySetting { Name = "Right side window heat", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_WindowHeatSw4" },
new PMDGVerbositySetting { Name = "Wing anti-ice", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_WingAntiIceSw" },
new PMDGVerbositySetting { Name = "Engine #1 anti-ice", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_EngAntiIceSw1" },
new PMDGVerbositySetting { Name = "Engine #2 anti-ice", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_EngAntiIceSw2" },
new PMDGVerbositySetting { Name = "Left side window overheat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunOVERHEAT1" },
new PMDGVerbositySetting { Name = "Left forwardwindow overheat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunOVERHEAT2" },
new PMDGVerbositySetting { Name = "Right forward window overheat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunOVERHEAT3" },
new PMDGVerbositySetting { Name = "Right side window overheat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunOVERHEAT4" },
new PMDGVerbositySetting { Name = "Left side window heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunON1" },
new PMDGVerbositySetting { Name = "Left forward window heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunON2" },
new PMDGVerbositySetting { Name = "Right forward window heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunON3" },
new PMDGVerbositySetting { Name = "Right side window heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunON4" },
new PMDGVerbositySetting { Name = "Captain's pitot heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunCAPT_PITOT" },
new PMDGVerbositySetting { Name = "Left elevator pitot heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunL_ELEV_PITOT" },
new PMDGVerbositySetting { Name = "Left alpha vane light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunL_ALPHA_VANE" },
new PMDGVerbositySetting { Name = "Left temp probe light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunL_TEMP_PROBE" },
new PMDGVerbositySetting { Name = "F/O pito heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunFO_PITOT" },
new PMDGVerbositySetting { Name = "Right elevator pitot heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunR_ELEV_PITOT" },
new PMDGVerbositySetting { Name = "Right alpha vane light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunR_ALPHA_VANE" },
new PMDGVerbositySetting { Name = "Aux pitot heat light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunAUX_PITOT" },
new PMDGVerbositySetting { Name = "Left anti-ice valve", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunVALVE_OPEN1" },
new PMDGVerbositySetting { Name = "Right anti-ice valve", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunVALVE_OPEN2" },
new PMDGVerbositySetting { Name = "Left cowl anti-ice light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunCOWL_ANTI_ICE1" },
new PMDGVerbositySetting { Name = "Right cowl anti-ice light", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunCOWL_ANTI_ICE2" },
new PMDGVerbositySetting { Name = "Left cowl valve", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunCOWL_VALVE_OPEN1" },
new PMDGVerbositySetting { Name = "Right cowl valve", PanelName = "Center Overhead", PanelSection = "Anti-ice", SettingKey = "ICE_annunCOWL_VALVE_OPEN2" },

// --section: Hydraulics
new PMDGVerbositySetting { Name = "Electric Hydraulic pump #1", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_PumpSw_elec1" },
new PMDGVerbositySetting { Name = "Electric Hydraulic pump #2", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_PumpSw_elec2" },
new PMDGVerbositySetting { Name = "Engine #1 Hydraulic pump", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_PumpSw_eng1" },
new PMDGVerbositySetting { Name = "Engine #2 Hydraulic pump", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_PumpSw_eng2" },
new PMDGVerbositySetting { Name = "Engine #1 hydraulic pump low pressure light", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_annunLOW_PRESS_eng1" },
new PMDGVerbositySetting { Name = "Engine #2 hydraulic pump low pressure light", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_annunLOW_PRESS_eng2" },
new PMDGVerbositySetting { Name = "Electric hydraulic pump #1 low pressure light", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_annunLOW_PRESS_elec1" },
new PMDGVerbositySetting { Name = "Electric hydraulic pump #2 low pressure light", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_annunLOW_PRESS_elec2" },
new PMDGVerbositySetting { Name = "Electric hydraulic pump #1 overheat light", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_annunOVERHEAT_elec1" },
new PMDGVerbositySetting { Name = "Electric hydraulic pump #2 overheat light", PanelName = "Center Overhead", PanelSection = "Hydraulics", SettingKey = "HYD_annunOVERHEAT_elec2" },
// --section: Air systems
new PMDGVerbositySetting { Name = "Air source", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_TempSourceSelector" },
new PMDGVerbositySetting { Name = "Air trim", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_TrimAirSwitch" },
new PMDGVerbositySetting { Name = "Flight deck temprature light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunZoneTemp1" },
new PMDGVerbositySetting { Name = "Forward cabin temprature light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunZoneTemp2" },
new PMDGVerbositySetting { Name = "AFT cabin temprature light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunZoneTemp3" },
new PMDGVerbositySetting { Name = "Dual bleed light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunDualBleed" },
new PMDGVerbositySetting { Name = "Left ram door light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunRamDoorL" },
new PMDGVerbositySetting { Name = "Right ram door light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunRamDoorR" },
new PMDGVerbositySetting { Name = "Left recirc fan", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_RecircFanSwitch1" },
new PMDGVerbositySetting { Name = "Right recirc fan", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_RecircFanSwitch2" },
new PMDGVerbositySetting { Name = "Left pack", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_PackSwitch1" },
new PMDGVerbositySetting { Name = "Right pack", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_PackSwitch2" },
new PMDGVerbositySetting { Name = "Left air bleed", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_BleedAirSwitch1" },
new PMDGVerbositySetting { Name = "Right air bleed", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_BleedAirSwitch2" },
new PMDGVerbositySetting { Name = "APU bleed", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_APUBleedAirSwitch" },
new PMDGVerbositySetting { Name = "Isolation valve", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_IsolationValveSwitch" },
new PMDGVerbositySetting { Name = "Left pack trip light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunPackTripOff1" },
new PMDGVerbositySetting { Name = "Right pack trip light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunPackTripOff2" },
new PMDGVerbositySetting { Name = "Left wing overheat light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunWingBodyOverheat1" },
new PMDGVerbositySetting { Name = "Right wing overheat light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunWingBodyOverheat2" },
new PMDGVerbositySetting { Name = "Left bleed trip light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunBleedTripOff1" },
new PMDGVerbositySetting { Name = "Right bleed trip light", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_annunBleedTripOff2" },
new PMDGVerbositySetting { Name = "Flight altitude", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_DisplayFltAlt" },
new PMDGVerbositySetting { Name = "Landing altitude", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_DisplayLandAlt" },
new PMDGVerbositySetting { Name = "Outflow valve", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_OutflowValveSwitch" },
new PMDGVerbositySetting { Name = "Pressurization mode selector", PanelName = "Center Overhead", PanelSection = "Air Systems", SettingKey = "AIR_PressurizationModeSelector" },

// ---Panel: Bottom Overhead
// ---section: Engines

new PMDGVerbositySetting { Name = "APU selector", PanelName = "Bottom Overhead", PanelSection = "Engines", SettingKey = "APU_Selector" },
new PMDGVerbositySetting { Name = "Engine #1", PanelName = "Bottom Overhead", PanelSection = "Engines", SettingKey = "ENG_StartSelector1" },
new PMDGVerbositySetting { Name = "Engine #2", PanelName = "Bottom Overhead", PanelSection = "Engines", SettingKey = "ENG_StartSelector2" },
new PMDGVerbositySetting { Name = "Ignition start selector", PanelName = "Bottom Overhead", PanelSection = "Engines", SettingKey = "ENG_IgnitionSelector" },

// --section: lights
new PMDGVerbositySetting {Name = "Left retractable landing light", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_LandingLtRetractableSw1" },
new PMDGVerbositySetting {Name = "Right retractable landing light", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_LandingLtRetractableSw2" },
new PMDGVerbositySetting{ Name = "Left fixed landing light", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_LandingLtFixedSw1" },
new PMDGVerbositySetting{ Name = "Right fixed landing light", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_LandingLtFixedSw2" },
new PMDGVerbositySetting { Name = "Left runway turnoff light", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_RunwayTurnoffSw1" },
new PMDGVerbositySetting { Name = "Right runway turnoff light", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_RunwayTurnoffSw2" },
new PMDGVerbositySetting { Name = "Taxi light", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_TaxiSw" },
new PMDGVerbositySetting { Name = "Logo lights", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_LogoSw" },
new PMDGVerbositySetting { Name = "Position lights", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_PositionSw" },
new PMDGVerbositySetting { Name = "Anti-collision lights", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_AntiCollisionSw" },
new PMDGVerbositySetting { Name = "Wing lights", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_WingSw" },
new PMDGVerbositySetting { Name = "Wheel well lights", PanelName = "Bottom Overhead", PanelSection = "Lights", SettingKey = "LTS_WheelWellSw" },

// --panel: Glare Shield
// --section: Warnings
new PMDGVerbositySetting {Name = "Left fire warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunFIRE_WARN1" },
new PMDGVerbositySetting {Name = "Right fire warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunFIRE_WARN2" },
new PMDGVerbositySetting { Name = "Left master caution light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunMASTER_CAUTION1" },
new PMDGVerbositySetting { Name = "Right master caution light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunMASTER_CAUTION2" },
new PMDGVerbositySetting { Name = "Flight controls warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunFLT_CONT" },
new PMDGVerbositySetting { Name = "IRS warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunIRS" },
new PMDGVerbositySetting { Name = "Fuel warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunFUEL" },
new PMDGVerbositySetting { Name = "Electrical warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunELEC" },
new PMDGVerbositySetting { Name = "APU warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunAPU" },
new PMDGVerbositySetting { Name = "Overheat warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunOVHT_DET" },
new PMDGVerbositySetting { Name = "Anti-ice warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunANTI_ICE" },
new PMDGVerbositySetting { Name = "Hydraulics warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunHYD" },
new PMDGVerbositySetting { Name = "Doors warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunDOORS" },
new PMDGVerbositySetting { Name = "Engines warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunENG" },
new PMDGVerbositySetting { Name = "Overhead warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunOVERHEAD" },
new PMDGVerbositySetting { Name = "Air Systems warning light", PanelName = "Glare Shield", PanelSection = "Warnings", SettingKey = "WARN_annunAIR_COND" },

// --section: MCP
new PMDGVerbositySetting { Name = "MCP power", PanelName = "MCP", PanelSection = "MCP", SettingKey = "MCP_indication_powered" },
new PMDGVerbositySetting { Name = "Speed intervene", PanelName = "Glare Shield", PanelSection = "MCP-SPEED", SettingKey = "MCP_IASBlank" },
new PMDGVerbositySetting { Name = "MCP Overspeed warning", PanelName = "Glare Shield", PanelSection = "MCP-SPEED", SettingKey = "MCP_IASOverspeedFlash" },
new PMDGVerbositySetting { Name = "MCP underspeed warning", PanelName = "Glare Shield", PanelSection = "MCP-SPEED", SettingKey = "MCP_IASUnderspeedFlash" },
new PMDGVerbositySetting { Name = "Autothrottle", PanelName = "Glare Shield", PanelSection = "MCP-SPEED", SettingKey = "MCP_ATArmSw" },
new PMDGVerbositySetting { Name = "Autothrottle armed light", PanelName = "Glare Shield", PanelSection = "MCP-SPEED", SettingKey = "MCP_annunATArm" },
new PMDGVerbositySetting { Name = "N1 light", PanelName = "Glare Shield", PanelSection = "MCP-SPEED", SettingKey = "MCP_annunN1" },
new PMDGVerbositySetting { Name = "Speed light", PanelName = "Glare Shield", PanelSection = "MCP-SPEED", SettingKey = "MCP_annunSPEED" },
new PMDGVerbositySetting { Name = "Heading select light", PanelName = "Glare Shield", PanelSection = "MCP-HEADING", SettingKey = "MCP_annunHDG_SEL" },
new PMDGVerbositySetting { Name = "LNav light", PanelName = "Glare Shield", PanelSection = "MCP-HEADING", SettingKey = "MCP_annunLNAV" },
new PMDGVerbositySetting { Name = "Vertical speed mode", PanelName = "Glare Shield", PanelSection = "MCP-VERTICAL", SettingKey = "MCP_VertSpeedBlank" },
new PMDGVerbositySetting { Name = "Vertical speed light", PanelName = "Glare Shield", PanelSection = "MCP-VERTICAL", SettingKey = "MCP_annunVS" },
new PMDGVerbositySetting { Name = "V NAV light", PanelName = "Glare Shield", PanelSection = "MCP-ALTITUDE", SettingKey = "MCP_annunVNAV" },
new PMDGVerbositySetting { Name = "Level change light", PanelName = "Glare Shield", PanelSection = "MCP-ALTITUDE", SettingKey = "MCP_annunLVL_CHG" },
new PMDGVerbositySetting { Name = "Altitude hold light", PanelName = "Glare Shield", PanelSection = "MCP-ALTITUDE", SettingKey = "MCP_annunALT_HOLD" },
new PMDGVerbositySetting { Name = "Left flight director", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_FDSw1" },
new PMDGVerbositySetting { Name = "Right flight director", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_FDSw2" },
new PMDGVerbositySetting { Name = "Bank limit", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_BankLimitSel" },
new PMDGVerbositySetting { Name = "Disengage bar", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_DisengageBar" },
new PMDGVerbositySetting { Name = "Left flight director light", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_annunFD1" },
new PMDGVerbositySetting { Name = "Right flight director light", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_annunFD2" },
new PMDGVerbositySetting { Name = "Approach mode light", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_annunAPP" },
new PMDGVerbositySetting { Name = "VOR/Localizer light", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_annunVOR_LOC" },
new PMDGVerbositySetting { Name = "CMDA light", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_annunCMD_A" },
new PMDGVerbositySetting { Name = "CWSA light", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATJION", SettingKey = "MCP_annunCWS_A" },
new PMDGVerbositySetting { Name = "CMDB light", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_annunCMD_B" },
new PMDGVerbositySetting { Name = "CWSB", PanelName = "Glare Shield", PanelSection = "MCP-NAVIGATION", SettingKey = "MCP_annunCWS_B" },
// ---panel: forward
// --section: main

new PMDGVerbositySetting { Name = "Auto brake", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_AutobrakeSelector" },
new PMDGVerbositySetting { Name = "Speed brake armed light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunSPEEDBRAKE_ARMED" },
new PMDGVerbositySetting { Name = "Speed brake extended light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunSPEEDBRAKE_EXTENDED" },
new PMDGVerbositySetting { Name = "Speedbrake d/n arm light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunSPEEDBRAKE_DO_NOT_ARM" },
new PMDGVerbositySetting { Name = "Autobrake disarm light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAUTO_BRAKE_DISARM" },
new PMDGVerbositySetting { Name = "N1", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_N1SetSelector" },
new PMDGVerbositySetting {Name = "Nose wheel stearing", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_NoseWheelSteeringSwNORM" },
new PMDGVerbositySetting { Name = "Left Disengage test selector", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_DisengageTestSelector1" },
new PMDGVerbositySetting { Name = "Right Disengage test selector", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_DisengageTestSelector2" },
new PMDGVerbositySetting { Name = "Interior lights", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_LightsSelector" },
new PMDGVerbositySetting { Name = "Fuel flow selector", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_FuelFlowSelector" },
new PMDGVerbositySetting { Name = "Left below glide slope light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunBELOW_GS1" },
new PMDGVerbositySetting { Name = "Right below glide slope light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunBELOW_GS2" },
new PMDGVerbositySetting { Name = "Red command A disengage light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAP1" },
new PMDGVerbositySetting { Name = "Amber command A disengage light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAP_Amber1" },
new PMDGVerbositySetting { Name = "Red command B disengage light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAP2" },
new PMDGVerbositySetting { Name = "Amber command B disengage light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAP_Amber2" },
new PMDGVerbositySetting { Name = "Red left auto throttle disengage light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAT1" },
new PMDGVerbositySetting { Name = "Red right auto throttle disengage light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAT2" },
new PMDGVerbositySetting { Name = "Amber left auto throttle disengage light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAT_Amber1" },
new PMDGVerbositySetting { Name = "Amber right auto throttle disengage light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunAT_Amber2" },
new PMDGVerbositySetting { Name = "Left FMC light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunFMC1" },
new PMDGVerbositySetting { Name = "Right FMC light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunFMC2" },
new PMDGVerbositySetting { Name = "Stab out of trim light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunSTAB_OUT_OF_TRIM" },
new PMDGVerbositySetting { Name = "Anti-skid inop light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunANTI_SKID_INOP" },
new PMDGVerbositySetting { Name = "Left DU selector", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_MainPanelDUSel1" },
new PMDGVerbositySetting { Name = "Right DU selector", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_MainPanelDUSel2" },
new PMDGVerbositySetting { Name = "Left lower DU selector", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_LowerDUSel1" },
new PMDGVerbositySetting { Name = "Right lower DU selector", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_LowerDUSel2" },
new PMDGVerbositySetting { Name = "RMI #1", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_RMISelector1_VOR" },
new PMDGVerbositySetting { Name = "RMI #2", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_RMISelector2_VOR" },
new PMDGVerbositySetting { Name = "Speed ref  selector", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_SpdRefSelector" },
new PMDGVerbositySetting { Name = "Break pressure needle", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_BrakePressNeedle" },
new PMDGVerbositySetting { Name = "Left flaps needle", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_TEFlapsNeedle1" },
new PMDGVerbositySetting { Name = "Right flaps needle", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_TEFlapsNeedle2" },
new PMDGVerbositySetting { Name = "Flaps in transit light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunLE_FLAPS_TRANSIT" },
new PMDGVerbositySetting { Name = "Flaps extended light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunLE_FLAPS_EXT" },
new PMDGVerbositySetting { Name = "Gear lever", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_GearLever" },
new PMDGVerbositySetting { Name = "Nose gear in transit light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunGEAR_transit_nose" },
new PMDGVerbositySetting { Name = "Left gear in transit light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunGEAR_transit_left" },
new PMDGVerbositySetting { Name = "Right gear in transit light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunGEAR_transit_right" },
new PMDGVerbositySetting { Name = "Nose gear locked light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunGEAR_locked_nose" },
new PMDGVerbositySetting { Name = "Left gear locked light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunGEAR_locked_left" },
new PMDGVerbositySetting { Name = "Right gear locked light", PanelName = "Forward", PanelSection = "Main", SettingKey = "MAIN_annunGEAR_locked_right" },

// --panel: Lower Forward
// --section: lights

new PMDGVerbositySetting { Name = "Left main panel lighting", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_MainPanelKnob1" },
new PMDGVerbositySetting { Name = "Right main panel lighting", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_MainPanelKnob2" },
new PMDGVerbositySetting { Name = "Main panel Backlight", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_BackgroundKnob" },
new PMDGVerbositySetting { Name = "AFDS flood light", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_AFDSFloodKnob" },
new PMDGVerbositySetting { Name = "Left outboard DU brightness", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_OutbdDUBrtKnob1" },
new PMDGVerbositySetting { Name = "Right outboard DU brightness", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_OutbdDUBrtKnob2" },
new PMDGVerbositySetting { Name = "Left inboard DU brightness", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_InbdDUBrtKnob1" },
new PMDGVerbositySetting { Name = "Right inboard DU brightness", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_InbdDUBrtKnob2" },
new PMDGVerbositySetting { Name = "Left inboard map brightness", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_InbdDUMapBrtKnob1" },
new PMDGVerbositySetting { Name = "Right inboard map brightness", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_InbdDUMapBrtKnob2" },
// new PMDGVerbositySetting { Name = "Upper DU brightness", PanelName = "Lower Forward", PanelSection = "Lights"" },
new PMDGVerbositySetting {Name = "Lower DU brightness", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_LowerDUBrtKnob" },
new PMDGVerbositySetting { Name = "Lower DU map brightness", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "LTS_LowerDUMapBrtKnob" },
new PMDGVerbositySetting { Name = "GPWS inop light", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "GPWS_annunINOP" },
new PMDGVerbositySetting { Name = "GPWS flaps inhibit", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "GPWS_FlapInhibitSw_NORM" },
new PMDGVerbositySetting { Name = "GPWS gear inhibit", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "GPWS_GearInhibitSw_NORM" },
new PMDGVerbositySetting { Name = "GPWS terrain inhibit", PanelName = "Lower Forward", PanelSection = "Lights", SettingKey = "GPWS_TerrInhibitSw_NORM" },


// --panel: Control Stand
// --section: CDU

new PMDGVerbositySetting {Name = "CDU #1 execute key", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunEXEC1" },
new PMDGVerbositySetting {Name = "CDU #2 execute key", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunEXEC2" },
new PMDGVerbositySetting { Name = "CDU #1 call light", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunCALL1" },
new PMDGVerbositySetting { Name = "CDU #2 call light", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunCALL2" },
new PMDGVerbositySetting { Name = "CDU #1 faill light", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunFAIL1" },
new PMDGVerbositySetting { Name = "CDU #2 faill light", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunFAIL2" },
new PMDGVerbositySetting { Name = "CDU #1 message light", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunMSG1" },
new PMDGVerbositySetting { Name = "CDU #2 message light", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunMSG2" },
new PMDGVerbositySetting { Name = "CDU #1 offset light", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunOFST1" },
new PMDGVerbositySetting { Name = "CDU #2 offset light", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_annunOFST2" },
new PMDGVerbositySetting { Name = "CDU #1 brightness", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_BrtKnob1" },
new PMDGVerbositySetting { Name = "CDU #2 brightness", PanelName = "Control Stand", PanelSection = "CDU", SettingKey = "CDU_BrtKnob2" },
new PMDGVerbositySetting { Name = "Electrical stab trim", PanelName = "Control Stand", PanelSection = "TRIM", SettingKey = "TRIM_StabTrimMainElecSw_NORMAL" },
new PMDGVerbositySetting { Name = "Auto pilot stab trim", PanelName = "Control Stand", PanelSection = "TRIM", SettingKey = "TRIM_StabTrimAutoPilotSw_NORMAL" },
new PMDGVerbositySetting { Name = "Stab trim", PanelName = "Control Stand", PanelSection = "TRIM", SettingKey = "TRIM_StabTrimSw_NORMAL" },
new PMDGVerbositySetting { Name = "Pedestal brightness", PanelName = "Control Stand", PanelSection = "PEDESTAL", SettingKey = "LTS_PedFloodKnob" },
new PMDGVerbositySetting { Name = "Pedestal panel brightness", PanelName = "Control Stand", PanelSection = "PEDESTAL", SettingKey = "LTS_PedPanelKnob" },
new PMDGVerbositySetting { Name = "Lock failure light", PanelName = "Control Stand", PanelSection = "PEDESTAL", SettingKey = "PED_annunLOCK_FAIL" },
new PMDGVerbositySetting { Name = "Auto unlock light", PanelName = "Control Stand", PanelSection = "PEDESTAL", SettingKey = "PED_annunAUTO_UNLK" },
new PMDGVerbositySetting { Name = "Flight deck door", PanelName = "Control Stand", PanelSection = "PEDESTAL", SettingKey = "PED_FltDkDoorSel" },
new PMDGVerbositySetting { Name = "Parking brake light", PanelName = "Control Stand", PanelSection = "PEDESTAL", SettingKey = "PED_annunParkingBrake" },
new PMDGVerbositySetting { Name = "Left overheat detector", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_OvhtDetSw1" },
new PMDGVerbositySetting { Name = "Right overheat detector", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_OvhtDetSw2" },
new PMDGVerbositySetting { Name = "Engine #1 overheat light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunENG_OVERHEAT1" },
new PMDGVerbositySetting { Name = "Engine #2 overheat light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunENG_OVERHEAT2" },
new PMDGVerbositySetting { Name = "Fire detection test", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_DetTestSw" },
new PMDGVerbositySetting { Name = "Left fire handle", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_HandlePos1" },
new PMDGVerbositySetting { Name = "Right fire handle", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_HandlePos2" },
new PMDGVerbositySetting { Name = "APU fire handle", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_HandlePos3" },
new PMDGVerbositySetting { Name = "Left fire handle illuminated light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_HandleIlluminated1" },
new PMDGVerbositySetting { Name = "Right fire handle illuminated light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_HandleIlluminated2" },
new PMDGVerbositySetting { Name = "APU fire handle illuminated light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_HandleIlluminated3" },
new PMDGVerbositySetting { Name = "Wheel well fire light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunWHEEL_WELL" },
new PMDGVerbositySetting { Name = "Fire fault light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunFAULT" },
new PMDGVerbositySetting{Name = "APU fire detector inop light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunAPU_DET_INOP" },
new PMDGVerbositySetting { Name = "APU fire bottle discharge light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunAPU_BOTTLE_DISCHARGE" },
new PMDGVerbositySetting { Name = "Left fire bottle discharge light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunBOTTLE_DISCHARGE1" },
new PMDGVerbositySetting { Name = "Right fire bottle discharge light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunBOTTLE_DISCHARGE2" },
new PMDGVerbositySetting { Name = "Fire extinguisher test", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_ExtinguisherTestSw" },
new PMDGVerbositySetting { Name = "Left fire extinguisher test light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunExtinguisherTest1" },
new PMDGVerbositySetting { Name = "Right fire extinguisher test light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunExtinguisherTest2" },
new PMDGVerbositySetting { Name = "APU fire extinguisher test light", PanelName = "Control Stand", PanelSection = "FIRE", SettingKey = "FIRE_annunExtinguisherTest3" },

// --section: cargo fire

new PMDGVerbositySetting { Name = "Forward cargo fire extinguisher test light", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_annunExtTest1" },
new PMDGVerbositySetting { Name = "Aft cargo fire extinguisher test light", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_annunExtTest2" },
new PMDGVerbositySetting { Name = "Forward cargo fire detector", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_DetSelect1" },
new PMDGVerbositySetting { Name = "Aft cargo fire detector", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_DetSelect2" },
new PMDGVerbositySetting { Name = "Forward cargo fire detector armed", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_ArmedSw1" },
new PMDGVerbositySetting { Name = "Aft cargo fire detector armed", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_ArmedSw2" },
new PMDGVerbositySetting { Name = "Forward cargo fire light", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_annunFWD" },
new PMDGVerbositySetting { Name = "Aft cargo fire light", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_annunAFT" },
new PMDGVerbositySetting { Name = "Cargo fire detector fault light", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_annunDETECTOR_FAULT" },
new PMDGVerbositySetting { Name = "Cargo fire discharge light", PanelName = "Control Stand", PanelSection = "CARGO FIRE", SettingKey = "CARGO_annunDISCH" },

// --section: transponder

new PMDGVerbositySetting { Name = "Transponder source", PanelName = "Control Stand", PanelSection = "XPONDER", SettingKey = "XPDR_XpndrSelector_2" },
new PMDGVerbositySetting { Name = "Transponder alternate source", PanelName = "Control Stand", PanelSection = "XPONDER", SettingKey = "XPDR_AltSourceSel_2" },
new PMDGVerbositySetting { Name = "Transponder mode", PanelName = "Control Stand", PanelSection = "XPONDER", SettingKey = "XPDR_ModeSel" },
new PMDGVerbositySetting { Name = "Transponder failure light", PanelName = "Control Stand", PanelSection = "XPONDER", SettingKey = "XPDR_annunFAIL" },

// --panel: AFS
new PMDGVerbositySetting { Name = "Auto throttle servos", PanelName = "AFS", PanelSection = "AFS", SettingKey = "AFS_AutothrottleServosConnected" },
new PMDGVerbositySetting { Name = "Auto pitch", PanelName = "AFS", PanelSection = "AFS", SettingKey = "AFS_ControlsPitch" },
new PMDGVerbositySetting { Name = "Auto roll", PanelName = "AFS", PanelSection = "AFS", SettingKey = "AFS_ControlsRoll" },

// ---panel: buses
new PMDGVerbositySetting {Name = "DC bus: hot battery", PanelName = "Electrical", PanelSection = "BUSeS", SettingKey = "BUSSES_DC_HOT_BAT" },
new PMDGVerbositySetting { Name = "DC bus: hot battery switched", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_DC_HOT_BAT_SWITCHED" },
new PMDGVerbositySetting { Name = "DC bus: battery", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_DC_BUS1" },
new PMDGVerbositySetting {Name = "DC bus: standby", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_DC_STANDBY_BUS" },
new PMDGVerbositySetting { Name = "DC bus: bus #1", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_DC_BUS1" },
new PMDGVerbositySetting { Name = "DC bus: bus #2", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_DC_BUS2" },
new PMDGVerbositySetting { Name = "DC bus: ground svc", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_DC_GROUND_SVC" },
new PMDGVerbositySetting { Name = "AC bus: transfer #1", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_TRANSFER1" },
new PMDGVerbositySetting { Name = "AC bus: transfer #2", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_TRANSFER2" },
new PMDGVerbositySetting { Name = "AC bus: ground svc #1", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_GROUND_SVC1" },
new PMDGVerbositySetting { Name = "AC bus: ground svc #2", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_GROUND_SVC2" },
new PMDGVerbositySetting { Name = "AC bus: main #1", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_MAIN1" },
new PMDGVerbositySetting { Name = "AC bus: main #2", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_MAIN2" },
new PMDGVerbositySetting { Name = "AC bus: galley #1", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_GALLEY1" },
new PMDGVerbositySetting { Name = "AC bus: galley #2", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_GALLEY2" },
new PMDGVerbositySetting { Name = "AC bus: standby", PanelName = "Electrical", PanelSection = "BUSES", SettingKey = "BUSSES_AC_STANDBY" },

// Microphones and comms receivers. Uses a dictionary of <int, string> for the receiver bitmask.
new PMDGVerbositySetting {Name = "Captain's microphone", PanelName = "AUDIO", PanelSection = "AUDIO", SettingKey = "COMM_SelectedMic1" },
new PMDGVerbositySetting {Name = "First officer's microphone", PanelName = "AUDIO", PanelSection = "AUDIO", SettingKey = "COMM_SelectedMic2" },
new PMDGVerbositySetting {Name = "Observer's microphone", PanelName = "AUDIO", PanelSection = "AUDIO", SettingKey = "COMM_SelectedMic3" },
new PMDGVerbositySetting {Name = "Captain's comm receiver", PanelName = "AUDIO", PanelSection = "AUDIO", SettingKey = "COMM_ReceiverSwitches1" },
new PMDGVerbositySetting {Name = "First officer's comm receiver", PanelName = "AUDIO", PanelSection = "AUDIO", SettingKey = "COMM_ReceiverSwitches2" },
new PMDGVerbositySetting {Name = "Overhead comm receiver", PanelName = "AUDIO", PanelSection = "AUDIO", SettingKey = "COMM_ReceiverSwitches3" },
// --end-panel-controls                              
            };
        }

    }
}
