//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class pmdg737_offsets : global::System.Configuration.ApplicationSettingsBase {
        
        private static pmdg737_offsets defaultInstance = ((pmdg737_offsets)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new pmdg737_offsets())));
        
        public static pmdg737_offsets Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_DisplaySelector {
            get {
                return ((bool)(this["IRS_DisplaySelector"]));
            }
            set {
                this["IRS_DisplaySelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_SysDisplay_r {
            get {
                return ((bool)(this["IRS_SysDisplay_r"]));
            }
            set {
                this["IRS_SysDisplay_r"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunGPS {
            get {
                return ((bool)(this["IRS_annunGPS"]));
            }
            set {
                this["IRS_annunGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunALIGN_L {
            get {
                return ((bool)(this["IRS_annunALIGN_L"]));
            }
            set {
                this["IRS_annunALIGN_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunALIGN_R {
            get {
                return ((bool)(this["IRS_annunALIGN_R"]));
            }
            set {
                this["IRS_annunALIGN_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunON_DC_L {
            get {
                return ((bool)(this["IRS_annunON_DC_L"]));
            }
            set {
                this["IRS_annunON_DC_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunON_DC_R {
            get {
                return ((bool)(this["IRS_annunON_DC_R"]));
            }
            set {
                this["IRS_annunON_DC_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunFAULT_L {
            get {
                return ((bool)(this["IRS_annunFAULT_L"]));
            }
            set {
                this["IRS_annunFAULT_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunFAULT_R {
            get {
                return ((bool)(this["IRS_annunFAULT_R"]));
            }
            set {
                this["IRS_annunFAULT_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunDC_FAIL_L {
            get {
                return ((bool)(this["IRS_annunDC_FAIL_L"]));
            }
            set {
                this["IRS_annunDC_FAIL_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunDC_FAIL_R {
            get {
                return ((bool)(this["IRS_annunDC_FAIL_R"]));
            }
            set {
                this["IRS_annunDC_FAIL_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_ModeSelector_L {
            get {
                return ((bool)(this["IRS_ModeSelector_L"]));
            }
            set {
                this["IRS_ModeSelector_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_ModeSelector_R {
            get {
                return ((bool)(this["IRS_ModeSelector_R"]));
            }
            set {
                this["IRS_ModeSelector_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WARN_annunPSEU {
            get {
                return ((bool)(this["WARN_annunPSEU"]));
            }
            set {
                this["WARN_annunPSEU"] = value;
            }
        }
    }
}
