//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class pmdg747_offsets : global::System.Configuration.ApplicationSettingsBase {
        
        private static pmdg747_offsets defaultInstance = ((pmdg747_offsets)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new pmdg747_offsets())));
        
        public static pmdg747_offsets Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_IASBlank {
            get {
                return ((bool)(this["MCP_IASBlank"]));
            }
            set {
                this["MCP_IASBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunTHR {
            get {
                return ((bool)(this["MCP_annunTHR"]));
            }
            set {
                this["MCP_annunTHR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunSPD {
            get {
                return ((bool)(this["MCP_annunSPD"]));
            }
            set {
                this["MCP_annunSPD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_ATArm_Sw_On {
            get {
                return ((bool)(this["MCP_ATArm_Sw_On"]));
            }
            set {
                this["MCP_ATArm_Sw_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FCTL_Speedbrake_Lever {
            get {
                return ((bool)(this["FCTL_Speedbrake_Lever"]));
            }
            set {
                this["FCTL_Speedbrake_Lever"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BRAKES_AutobrakeSelector {
            get {
                return ((bool)(this["BRAKES_AutobrakeSelector"]));
            }
            set {
                this["BRAKES_AutobrakeSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunLNAV {
            get {
                return ((bool)(this["MCP_annunLNAV"]));
            }
            set {
                this["MCP_annunLNAV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunHDG_HOLD {
            get {
                return ((bool)(this["MCP_annunHDG_HOLD"]));
            }
            set {
                this["MCP_annunHDG_HOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunVNAV {
            get {
                return ((bool)(this["MCP_annunVNAV"]));
            }
            set {
                this["MCP_annunVNAV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunFLCH {
            get {
                return ((bool)(this["MCP_annunFLCH"]));
            }
            set {
                this["MCP_annunFLCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunALT_HOLD {
            get {
                return ((bool)(this["MCP_annunALT_HOLD"]));
            }
            set {
                this["MCP_annunALT_HOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_VertSpeedBlank {
            get {
                return ((bool)(this["MCP_VertSpeedBlank"]));
            }
            set {
                this["MCP_VertSpeedBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunVS {
            get {
                return ((bool)(this["MCP_annunVS"]));
            }
            set {
                this["MCP_annunVS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_FD_Sw_On_L {
            get {
                return ((bool)(this["MCP_FD_Sw_On_L"]));
            }
            set {
                this["MCP_FD_Sw_On_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_FD_Sw_On_R {
            get {
                return ((bool)(this["MCP_FD_Sw_On_R"]));
            }
            set {
                this["MCP_FD_Sw_On_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_BankLimitSel {
            get {
                return ((bool)(this["MCP_BankLimitSel"]));
            }
            set {
                this["MCP_BankLimitSel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_DisengageBar {
            get {
                return ((bool)(this["MCP_DisengageBar"]));
            }
            set {
                this["MCP_DisengageBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunAP_L {
            get {
                return ((bool)(this["MCP_annunAP_L"]));
            }
            set {
                this["MCP_annunAP_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunAP_C {
            get {
                return ((bool)(this["MCP_annunAP_C"]));
            }
            set {
                this["MCP_annunAP_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunAP_R {
            get {
                return ((bool)(this["MCP_annunAP_R"]));
            }
            set {
                this["MCP_annunAP_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunLOC {
            get {
                return ((bool)(this["MCP_annunLOC"]));
            }
            set {
                this["MCP_annunLOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_annunAPP {
            get {
                return ((bool)(this["MCP_annunAPP"]));
            }
            set {
                this["MCP_annunAPP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MCP_panelPowered {
            get {
                return ((bool)(this["MCP_panelPowered"]));
            }
            set {
                this["MCP_panelPowered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_GenFieldReset1 {
            get {
                return ((bool)(this["ELEC_GenFieldReset1"]));
            }
            set {
                this["ELEC_GenFieldReset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_GenFieldReset2 {
            get {
                return ((bool)(this["ELEC_GenFieldReset2"]));
            }
            set {
                this["ELEC_GenFieldReset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_GenFieldReset3 {
            get {
                return ((bool)(this["ELEC_GenFieldReset3"]));
            }
            set {
                this["ELEC_GenFieldReset3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_GenFieldReset4 {
            get {
                return ((bool)(this["ELEC_GenFieldReset4"]));
            }
            set {
                this["ELEC_GenFieldReset4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_APUFieldReset1 {
            get {
                return ((bool)(this["ELEC_APUFieldReset1"]));
            }
            set {
                this["ELEC_APUFieldReset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_APUFieldReset2 {
            get {
                return ((bool)(this["ELEC_APUFieldReset2"]));
            }
            set {
                this["ELEC_APUFieldReset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_SplitSystemBreaker {
            get {
                return ((bool)(this["ELEC_SplitSystemBreaker"]));
            }
            set {
                this["ELEC_SplitSystemBreaker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_annunGen_FIELD_OFF1 {
            get {
                return ((bool)(this["ELEC_annunGen_FIELD_OFF1"]));
            }
            set {
                this["ELEC_annunGen_FIELD_OFF1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_annunGen_FIELD_OFF2 {
            get {
                return ((bool)(this["ELEC_annunGen_FIELD_OFF2"]));
            }
            set {
                this["ELEC_annunGen_FIELD_OFF2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_annunGen_FIELD_OFF3 {
            get {
                return ((bool)(this["ELEC_annunGen_FIELD_OFF3"]));
            }
            set {
                this["ELEC_annunGen_FIELD_OFF3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_annunGen_FIELD_OFF4 {
            get {
                return ((bool)(this["ELEC_annunGen_FIELD_OFF4"]));
            }
            set {
                this["ELEC_annunGen_FIELD_OFF4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_annunAPU_FIELD_OFF1 {
            get {
                return ((bool)(this["ELEC_annunAPU_FIELD_OFF1"]));
            }
            set {
                this["ELEC_annunAPU_FIELD_OFF1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_annunAPU_FIELD_OFF2 {
            get {
                return ((bool)(this["ELEC_annunAPU_FIELD_OFF2"]));
            }
            set {
                this["ELEC_annunAPU_FIELD_OFF2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ELEC_annunSplitSystemBreaker_OPEN {
            get {
                return ((bool)(this["ELEC_annunSplitSystemBreaker_OPEN"]));
            }
            set {
                this["ELEC_annunSplitSystemBreaker_OPEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FUEL_Reserve23Xfer_Sw_OPEN {
            get {
                return ((bool)(this["FUEL_Reserve23Xfer_Sw_OPEN"]));
            }
            set {
                this["FUEL_Reserve23Xfer_Sw_OPEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FUEL_CWTScavengePump_Sw_ON {
            get {
                return ((bool)(this["FUEL_CWTScavengePump_Sw_ON"]));
            }
            set {
                this["FUEL_CWTScavengePump_Sw_ON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FCTL_WingHydValve_Sw_SHUT_OFF1 {
            get {
                return ((bool)(this["FCTL_WingHydValve_Sw_SHUT_OFF1"]));
            }
            set {
                this["FCTL_WingHydValve_Sw_SHUT_OFF1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FCTL_WingHydValve_Sw_SHUT_OFF2 {
            get {
                return ((bool)(this["FCTL_WingHydValve_Sw_SHUT_OFF2"]));
            }
            set {
                this["FCTL_WingHydValve_Sw_SHUT_OFF2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FCTL_WingHydValve_Sw_SHUT_OFF3 {
            get {
                return ((bool)(this["FCTL_WingHydValve_Sw_SHUT_OFF3"]));
            }
            set {
                this["FCTL_WingHydValve_Sw_SHUT_OFF3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FCTL_WingHydValve_Sw_SHUT_OFF4 {
            get {
                return ((bool)(this["FCTL_WingHydValve_Sw_SHUT_OFF4"]));
            }
            set {
                this["FCTL_WingHydValve_Sw_SHUT_OFF4"] = value;
            }
        }
    }
}
