//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class pmdg737_offsets : global::System.Configuration.ApplicationSettingsBase {
        
        private static pmdg737_offsets defaultInstance = ((pmdg737_offsets)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new pmdg737_offsets())));
        
        public static pmdg737_offsets Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_DisplaySelector {
            get {
                return ((bool)(this["IRS_DisplaySelector"]));
            }
            set {
                this["IRS_DisplaySelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_SysDisplay_r {
            get {
                return ((bool)(this["IRS_SysDisplay_r"]));
            }
            set {
                this["IRS_SysDisplay_r"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunGPS {
            get {
                return ((bool)(this["IRS_annunGPS"]));
            }
            set {
                this["IRS_annunGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunALIGN_L {
            get {
                return ((bool)(this["IRS_annunALIGN_L"]));
            }
            set {
                this["IRS_annunALIGN_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunALIGN_R {
            get {
                return ((bool)(this["IRS_annunALIGN_R"]));
            }
            set {
                this["IRS_annunALIGN_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunON_DC_L {
            get {
                return ((bool)(this["IRS_annunON_DC_L"]));
            }
            set {
                this["IRS_annunON_DC_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunON_DC_R {
            get {
                return ((bool)(this["IRS_annunON_DC_R"]));
            }
            set {
                this["IRS_annunON_DC_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunFAULT_L {
            get {
                return ((bool)(this["IRS_annunFAULT_L"]));
            }
            set {
                this["IRS_annunFAULT_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunFAULT_R {
            get {
                return ((bool)(this["IRS_annunFAULT_R"]));
            }
            set {
                this["IRS_annunFAULT_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunDC_FAIL_L {
            get {
                return ((bool)(this["IRS_annunDC_FAIL_L"]));
            }
            set {
                this["IRS_annunDC_FAIL_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_annunDC_FAIL_R {
            get {
                return ((bool)(this["IRS_annunDC_FAIL_R"]));
            }
            set {
                this["IRS_annunDC_FAIL_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_ModeSelector_L {
            get {
                return ((bool)(this["IRS_ModeSelector_L"]));
            }
            set {
                this["IRS_ModeSelector_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRS_ModeSelector_R {
            get {
                return ((bool)(this["IRS_ModeSelector_R"]));
            }
            set {
                this["IRS_ModeSelector_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WARN_annunPSEU {
            get {
                return ((bool)(this["WARN_annunPSEU"]));
            }
            set {
                this["WARN_annunPSEU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMM_ServiceInterphoneSw {
            get {
                return ((bool)(this["COMM_ServiceInterphoneSw"]));
            }
            set {
                this["COMM_ServiceInterphoneSw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LTS_DomeWhiteSw {
            get {
                return ((bool)(this["LTS_DomeWhiteSw"]));
            }
            set {
                this["LTS_DomeWhiteSw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENG_EECSwitch_1 {
            get {
                return ((bool)(this["ENG_EECSwitch_1"]));
            }
            set {
                this["ENG_EECSwitch_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENG_EECSwitch_2 {
            get {
                return ((bool)(this["ENG_EECSwitch_2"]));
            }
            set {
                this["ENG_EECSwitch_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENG_annunREVERSER_1 {
            get {
                return ((bool)(this["ENG_annunREVERSER_1"]));
            }
            set {
                this["ENG_annunREVERSER_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENG_annunREVERSER_2 {
            get {
                return ((bool)(this["ENG_annunREVERSER_2"]));
            }
            set {
                this["ENG_annunREVERSER_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENG_annunENGINE_CONTROL_1 {
            get {
                return ((bool)(this["ENG_annunENGINE_CONTROL_1"]));
            }
            set {
                this["ENG_annunENGINE_CONTROL_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENG_annunENGINE_CONTROL_2 {
            get {
                return ((bool)(this["ENG_annunENGINE_CONTROL_2"]));
            }
            set {
                this["ENG_annunENGINE_CONTROL_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENG_annunALTN_1 {
            get {
                return ((bool)(this["ENG_annunALTN_1"]));
            }
            set {
                this["ENG_annunALTN_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENG_annunALTN_2 {
            get {
                return ((bool)(this["ENG_annunALTN_2"]));
            }
            set {
                this["ENG_annunALTN_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OXY_Needle {
            get {
                return ((bool)(this["OXY_Needle"]));
            }
            set {
                this["OXY_Needle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OXY_SwNormal {
            get {
                return ((bool)(this["OXY_SwNormal"]));
            }
            set {
                this["OXY_SwNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OXY_annunPASS_OXY_ON {
            get {
                return ((bool)(this["OXY_annunPASS_OXY_ON"]));
            }
            set {
                this["OXY_annunPASS_OXY_ON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GEAR_annunOvhdNOSE {
            get {
                return ((bool)(this["GEAR_annunOvhdNOSE"]));
            }
            set {
                this["GEAR_annunOvhdNOSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GEAR_annunOvhdLEFT {
            get {
                return ((bool)(this["GEAR_annunOvhdLEFT"]));
            }
            set {
                this["GEAR_annunOvhdLEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GEAR_annunOvhdRIGHT {
            get {
                return ((bool)(this["GEAR_annunOvhdRIGHT"]));
            }
            set {
                this["GEAR_annunOvhdRIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FLTREC_SwNormal {
            get {
                return ((bool)(this["FLTREC_SwNormal"]));
            }
            set {
                this["FLTREC_SwNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FLTREC_annunOFF {
            get {
                return ((bool)(this["FLTREC_annunOFF"]));
            }
            set {
                this["FLTREC_annunOFF"] = value;
            }
        }
    }
}
