//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Weather : global::System.Configuration.ApplicationSettingsBase {
        
        private static Weather defaultInstance = ((Weather)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Weather())));
        
        public static Weather Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindLayer_UpperAltitude {
            get {
                return ((bool)(this["WindLayer_UpperAltitude"]));
            }
            set {
                this["WindLayer_UpperAltitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindLayer_Direction {
            get {
                return ((bool)(this["WindLayer_Direction"]));
            }
            set {
                this["WindLayer_Direction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindLayer_Speed {
            get {
                return ((bool)(this["WindLayer_Speed"]));
            }
            set {
                this["WindLayer_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindLayer_Gust {
            get {
                return ((bool)(this["WindLayer_Gust"]));
            }
            set {
                this["WindLayer_Gust"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindLayer_Visibility {
            get {
                return ((bool)(this["WindLayer_Visibility"]));
            }
            set {
                this["WindLayer_Visibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindLayer_Turbulence {
            get {
                return ((bool)(this["WindLayer_Turbulence"]));
            }
            set {
                this["WindLayer_Turbulence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindLayer_Shear {
            get {
                return ((bool)(this["WindLayer_Shear"]));
            }
            set {
                this["WindLayer_Shear"] = value;
            }
        }
    }
}
