//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class commandHelp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal commandHelp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tfm.commandHelp", typeof(commandHelp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open A2A aircraft manager.
        /// </summary>
        internal static string A2A_manager {
            get {
                return ResourceManager.GetString("A2A_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read above ground altitude.
        /// </summary>
        internal static string AGL_Altitude {
            get {
                return ResourceManager.GetString("AGL_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read aircraft heading.
        /// </summary>
        internal static string Aircraft_Heading {
            get {
                return ResourceManager.GetString("Aircraft_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open aircraft profile window.
        /// </summary>
        internal static string aircraft_profiles {
            get {
                return ResourceManager.GetString("aircraft_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autopilot command key..
        /// </summary>
        internal static string ap_Command_Key {
            get {
                return ResourceManager.GetString("ap_Command_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read last FMC message.
        /// </summary>
        internal static string ap_FMCMessage {
            get {
                return ResourceManager.GetString("ap_FMCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get autopilot airspeed.
        /// </summary>
        internal static string ap_Get_Airspeed {
            get {
                return ResourceManager.GetString("ap_Get_Airspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get altimeter.
        /// </summary>
        internal static string ap_Get_Altimeter {
            get {
                return ResourceManager.GetString("ap_Get_Altimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get autopilot altitude.
        /// </summary>
        internal static string ap_Get_Altitude {
            get {
                return ResourceManager.GetString("ap_Get_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current comm radio settings.
        /// </summary>
        internal static string ap_Get_Com_Radios {
            get {
                return ResourceManager.GetString("ap_Get_Com_Radios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get autopilot heading.
        /// </summary>
        internal static string ap_Get_Heading {
            get {
                return ResourceManager.GetString("ap_Get_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get mach speed.
        /// </summary>
        internal static string ap_Get_Mach_Speed {
            get {
                return ResourceManager.GetString("ap_Get_Mach_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get nav radio info.
        /// </summary>
        internal static string ap_Get_Nav_Radios {
            get {
                return ResourceManager.GetString("ap_Get_Nav_Radios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current transponder setting.
        /// </summary>
        internal static string ap_Get_Transponder {
            get {
                return ResourceManager.GetString("ap_Get_Transponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get autopilot vertical speed.
        /// </summary>
        internal static string ap_Get_Vertical_Speed {
            get {
                return ResourceManager.GetString("ap_Get_Vertical_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring up nav radio dialog.
        /// </summary>
        internal static string ap_NavigationBox {
            get {
                return ResourceManager.GetString("ap_NavigationBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access PMDG CDU.
        /// </summary>
        internal static string ap_PMDG_CDU {
            get {
                return ResourceManager.GetString("ap_PMDG_CDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PMDG panels.
        /// </summary>
        internal static string ap_PMDG_Panels {
            get {
                return ResourceManager.GetString("ap_PMDG_Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set autopilot airspeed.
        /// </summary>
        internal static string ap_Set_Airspeed {
            get {
                return ResourceManager.GetString("ap_Set_Airspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set altimeter.
        /// </summary>
        internal static string ap_Set_Altimeter {
            get {
                return ResourceManager.GetString("ap_Set_Altimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set autopilot altitude.
        /// </summary>
        internal static string ap_Set_Altitude {
            get {
                return ResourceManager.GetString("ap_Set_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set comm radios.
        /// </summary>
        internal static string ap_Set_Com_Radios {
            get {
                return ResourceManager.GetString("ap_Set_Com_Radios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set autopilot heading.
        /// </summary>
        internal static string ap_Set_Heading {
            get {
                return ResourceManager.GetString("ap_Set_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set mach speed.
        /// </summary>
        internal static string ap_Set_Mach_Speed {
            get {
                return ResourceManager.GetString("ap_Set_Mach_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set nav radios.
        /// </summary>
        internal static string ap_Set_Nav_Radios {
            get {
                return ResourceManager.GetString("ap_Set_Nav_Radios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set spoilers.
        /// </summary>
        internal static string ap_set_spoilers {
            get {
                return ResourceManager.GetString("ap_set_spoilers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set throttle.
        /// </summary>
        internal static string ap_Set_Throttle {
            get {
                return ResourceManager.GetString("ap_Set_Throttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set  transponder.
        /// </summary>
        internal static string ap_Set_Transponder {
            get {
                return ResourceManager.GetString("ap_Set_Transponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set vertical speed.
        /// </summary>
        internal static string ap_Set_Vertical_Speed {
            get {
                return ResourceManager.GetString("ap_Set_Vertical_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit application.
        /// </summary>
        internal static string application_quit {
            get {
                return ResourceManager.GetString("application_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        internal static string application_settings {
            get {
                return ResourceManager.GetString("application_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart TFM.
        /// </summary>
        internal static string ApplicationRestart {
            get {
                return ResourceManager.GetString("ApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get above sea level altitude.
        /// </summary>
        internal static string ASL_Altitude {
            get {
                return ResourceManager.GetString("ASL_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle attitude mode.
        /// </summary>
        internal static string Attitude_Mode {
            get {
                return ResourceManager.GetString("Attitude_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command key.
        /// </summary>
        internal static string Command_Key {
            get {
                return ResourceManager.GetString("Command_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current location of aircraft.
        /// </summary>
        internal static string Current_Location {
            get {
                return ResourceManager.GetString("Current_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get destination info.
        /// </summary>
        internal static string Destination_Info {
            get {
                return ResourceManager.GetString("Destination_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get destination runway.
        /// </summary>
        internal static string destination_runway {
            get {
                return ResourceManager.GetString("destination_runway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Command Key.
        /// </summary>
        internal static string Disable_Command_Key {
            get {
                return ResourceManager.GetString("Disable_Command_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TFM website.
        /// </summary>
        internal static string display_website {
            get {
                return ResourceManager.GetString("display_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get distance to descent.
        /// </summary>
        internal static string distanceToDescent {
            get {
                return ResourceManager.GetString("distanceToDescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine 1 Info.
        /// </summary>
        internal static string Engine_1_Info {
            get {
                return ResourceManager.GetString("Engine_1_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine 1 Throttle.
        /// </summary>
        internal static string Engine_1_Throttle {
            get {
                return ResourceManager.GetString("Engine_1_Throttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine 2 Info.
        /// </summary>
        internal static string Engine_2_Info {
            get {
                return ResourceManager.GetString("Engine_2_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine 2 Throttle.
        /// </summary>
        internal static string Engine_2_Throttle {
            get {
                return ResourceManager.GetString("Engine_2_Throttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine 3 Info.
        /// </summary>
        internal static string Engine_3_Info {
            get {
                return ResourceManager.GetString("Engine_3_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine 3 Throttle.
        /// </summary>
        internal static string Engine_3_Throttle {
            get {
                return ResourceManager.GetString("Engine_3_Throttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine 4 Info.
        /// </summary>
        internal static string Engine_4_Info {
            get {
                return ResourceManager.GetString("Engine_4_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine 4 Throttle.
        /// </summary>
        internal static string Engine_4_Throttle {
            get {
                return ResourceManager.GetString("Engine_4_Throttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flight planner.
        /// </summary>
        internal static string flight_planner {
            get {
                return ResourceManager.GetString("flight_planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get fuel flow.
        /// </summary>
        internal static string Fuel_Flow {
            get {
                return ResourceManager.GetString("Fuel_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Fuel Manager.
        /// </summary>
        internal static string Fuel_Manager {
            get {
                return ResourceManager.GetString("Fuel_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get fuel report.
        /// </summary>
        internal static string Fuel_Report {
            get {
                return ResourceManager.GetString("Fuel_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 1 info.
        /// </summary>
        internal static string Fuel_Tank_1 {
            get {
                return ResourceManager.GetString("Fuel_Tank_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 10 info.
        /// </summary>
        internal static string Fuel_Tank_10 {
            get {
                return ResourceManager.GetString("Fuel_Tank_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 2 info.
        /// </summary>
        internal static string Fuel_Tank_2 {
            get {
                return ResourceManager.GetString("Fuel_Tank_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 3 info.
        /// </summary>
        internal static string Fuel_Tank_3 {
            get {
                return ResourceManager.GetString("Fuel_Tank_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 4 info.
        /// </summary>
        internal static string Fuel_Tank_4 {
            get {
                return ResourceManager.GetString("Fuel_Tank_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 5 info.
        /// </summary>
        internal static string Fuel_Tank_5 {
            get {
                return ResourceManager.GetString("Fuel_Tank_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 6 info.
        /// </summary>
        internal static string Fuel_Tank_6 {
            get {
                return ResourceManager.GetString("Fuel_Tank_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 7 info.
        /// </summary>
        internal static string Fuel_Tank_7 {
            get {
                return ResourceManager.GetString("Fuel_Tank_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 8 info.
        /// </summary>
        internal static string Fuel_Tank_8 {
            get {
                return ResourceManager.GetString("Fuel_Tank_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Tank 9 info.
        /// </summary>
        internal static string Fuel_Tank_9 {
            get {
                return ResourceManager.GetString("Fuel_Tank_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get speedbreak.
        /// </summary>
        internal static string get_speedbreak {
            get {
                return ResourceManager.GetString("get_speedbreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get spoilers.
        /// </summary>
        internal static string get_spoilers {
            get {
                return ResourceManager.GetString("get_spoilers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Speedread Ground speed.
        /// </summary>
        internal static string Ground_Speed {
            get {
                return ResourceManager.GetString("Ground_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read indicated airspeed.
        /// </summary>
        internal static string Indicated_Airspeed {
            get {
                return ResourceManager.GetString("Indicated_Airspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpToGate.
        /// </summary>
        internal static string JumpToGate {
            get {
                return ResourceManager.GetString("JumpToGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JumpToRunway.
        /// </summary>
        internal static string JumpToRunway {
            get {
                return ResourceManager.GetString("JumpToRunway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Keyboard Manager.
        /// </summary>
        internal static string keyboard_manager {
            get {
                return ResourceManager.GetString("keyboard_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get landing rate.
        /// </summary>
        internal static string Landing_Rate {
            get {
                return ResourceManager.GetString("Landing_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get local time.
        /// </summary>
        internal static string LocalTime {
            get {
                return ResourceManager.GetString("LocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get Mach speed.
        /// </summary>
        internal static string Mach_Speed {
            get {
                return ResourceManager.GetString("Mach_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle reading of SimConnect messages.
        /// </summary>
        internal static string Mute_Simconnect_Messages {
            get {
                return ResourceManager.GetString("Mute_Simconnect_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n1monitor.
        /// </summary>
        internal static string n1monitor {
            get {
                return ResourceManager.GetString("n1monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Airborn Aircraft.
        /// </summary>
        internal static string Nearby_Airborn_Aircraft {
            get {
                return ResourceManager.GetString("Nearby_Airborn_Aircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Ground Aircraft.
        /// </summary>
        internal static string Nearby_Ground_Aircraft {
            get {
                return ResourceManager.GetString("Nearby_Ground_Aircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest City.
        /// </summary>
        internal static string Nearest_City {
            get {
                return ResourceManager.GetString("Nearest_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Waypoint.
        /// </summary>
        internal static string Next_Waypoint {
            get {
                return ResourceManager.GetString("Next_Waypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output History.
        /// </summary>
        internal static string Output_History {
            get {
                return ResourceManager.GetString("Output_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside Temperature.
        /// </summary>
        internal static string Outside_Temperature {
            get {
                return ResourceManager.GetString("Outside_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Flaps Angle.
        /// </summary>
        internal static string Read_Flaps_Angle {
            get {
                return ResourceManager.GetString("Read_Flaps_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Landing Gear.
        /// </summary>
        internal static string Read_Landing_Gear {
            get {
                return ResourceManager.GetString("Read_Landing_Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Simulation Rate.
        /// </summary>
        internal static string Read_Simulation_Rate {
            get {
                return ResourceManager.GetString("Read_Simulation_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Last Simconnect Message.
        /// </summary>
        internal static string Repeat_Last_Simconnect_Message {
            get {
                return ResourceManager.GetString("Repeat_Last_Simconnect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report issue.
        /// </summary>
        internal static string report_issue {
            get {
                return ResourceManager.GetString("report_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runway Guidance Mode.
        /// </summary>
        internal static string Runway_Guidance_Mode {
            get {
                return ResourceManager.GetString("Runway_Guidance_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak Attitude.
        /// </summary>
        internal static string Speak_Attitude {
            get {
                return ResourceManager.GetString("Speak_Attitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takeoff assist.
        /// </summary>
        internal static string takeoff_assist {
            get {
                return ResourceManager.GetString("takeoff_assist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Autopilot Announcement.
        /// </summary>
        internal static string Toggle_Autopilot_Announcement {
            get {
                return ResourceManager.GetString("Toggle_Autopilot_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Braille output.
        /// </summary>
        internal static string Toggle_Braille_output {
            get {
                return ResourceManager.GetString("Toggle_Braille_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Flaps Announcement.
        /// </summary>
        internal static string Toggle_Flaps_Announcement {
            get {
                return ResourceManager.GetString("Toggle_Flaps_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle GPWS Announcement.
        /// </summary>
        internal static string Toggle_GPWS_Announcement {
            get {
                return ResourceManager.GetString("Toggle_GPWS_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle ILS Announcement.
        /// </summary>
        internal static string Toggle_ILS_Announcement {
            get {
                return ResourceManager.GetString("Toggle_ILS_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Trim Announcement.
        /// </summary>
        internal static string Toggle_Trim_Announcement {
            get {
                return ResourceManager.GetString("Toggle_Trim_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read True Airspeed.
        /// </summary>
        internal static string True_Airspeed {
            get {
                return ResourceManager.GetString("True_Airspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Vertical Speed.
        /// </summary>
        internal static string Vertical_Speed {
            get {
                return ResourceManager.GetString("Vertical_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Report.
        /// </summary>
        internal static string Weight_Report {
            get {
                return ResourceManager.GetString("Weight_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Information.
        /// </summary>
        internal static string Wind_Information {
            get {
                return ResourceManager.GetString("Wind_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read current ZuluTime.
        /// </summary>
        internal static string ZuluTime {
            get {
                return ResourceManager.GetString("ZuluTime", resourceCulture);
            }
        }
    }
}
