//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tfm.Keyboard_manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tfm.Keyboard_manager.KeyNames", typeof(KeyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad +.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        internal static string Alt {
            get {
                return ResourceManager.GetString("Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Back.
        /// </summary>
        internal static string BrowserBack {
            get {
                return ResourceManager.GetString("BrowserBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Favorites.
        /// </summary>
        internal static string BrowserFavorites {
            get {
                return ResourceManager.GetString("BrowserFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Forward.
        /// </summary>
        internal static string BrowserForward {
            get {
                return ResourceManager.GetString("BrowserForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Home.
        /// </summary>
        internal static string BrowserHome {
            get {
                return ResourceManager.GetString("BrowserHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Refresh.
        /// </summary>
        internal static string BrowserRefresh {
            get {
                return ResourceManager.GetString("BrowserRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Search.
        /// </summary>
        internal static string BrowserSearch {
            get {
                return ResourceManager.GetString("BrowserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Stop.
        /// </summary>
        internal static string BrowserStop {
            get {
                return ResourceManager.GetString("BrowserStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock.
        /// </summary>
        internal static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock.
        /// </summary>
        internal static string CapsLock {
            get {
                return ResourceManager.GetString("CapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string ControlKey {
            get {
                return ResourceManager.GetString("ControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad ..
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad /.
        /// </summary>
        internal static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Arrow.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10.
        /// </summary>
        internal static string F10 {
            get {
                return ResourceManager.GetString("F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F11.
        /// </summary>
        internal static string F11 {
            get {
                return ResourceManager.GetString("F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F12.
        /// </summary>
        internal static string F12 {
            get {
                return ResourceManager.GetString("F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F13.
        /// </summary>
        internal static string F13 {
            get {
                return ResourceManager.GetString("F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F14.
        /// </summary>
        internal static string F14 {
            get {
                return ResourceManager.GetString("F14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F15.
        /// </summary>
        internal static string F15 {
            get {
                return ResourceManager.GetString("F15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F16.
        /// </summary>
        internal static string F16 {
            get {
                return ResourceManager.GetString("F16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F17.
        /// </summary>
        internal static string F17 {
            get {
                return ResourceManager.GetString("F17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F18.
        /// </summary>
        internal static string F18 {
            get {
                return ResourceManager.GetString("F18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F19.
        /// </summary>
        internal static string F19 {
            get {
                return ResourceManager.GetString("F19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2.
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F20.
        /// </summary>
        internal static string F20 {
            get {
                return ResourceManager.GetString("F20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F21.
        /// </summary>
        internal static string F21 {
            get {
                return ResourceManager.GetString("F21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F22.
        /// </summary>
        internal static string F22 {
            get {
                return ResourceManager.GetString("F22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F23.
        /// </summary>
        internal static string F23 {
            get {
                return ResourceManager.GetString("F23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F24.
        /// </summary>
        internal static string F24 {
            get {
                return ResourceManager.GetString("F24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3.
        /// </summary>
        internal static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4.
        /// </summary>
        internal static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5.
        /// </summary>
        internal static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6.
        /// </summary>
        internal static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7.
        /// </summary>
        internal static string F7 {
            get {
                return ResourceManager.GetString("F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8.
        /// </summary>
        internal static string F8 {
            get {
                return ResourceManager.GetString("F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        internal static string F9 {
            get {
                return ResourceManager.GetString("F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        internal static string J {
            get {
                return ResourceManager.GetString("J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Favorite Application 1.
        /// </summary>
        internal static string LaunchApplication1 {
            get {
                return ResourceManager.GetString("LaunchApplication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Favorite Application 2.
        /// </summary>
        internal static string LaunchApplication2 {
            get {
                return ResourceManager.GetString("LaunchApplication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Mail.
        /// </summary>
        internal static string LaunchMail {
            get {
                return ResourceManager.GetString("LaunchMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control (Left).
        /// </summary>
        internal static string LControlKey {
            get {
                return ResourceManager.GetString("LControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arrow.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt (Left).
        /// </summary>
        internal static string LMenu {
            get {
                return ResourceManager.GetString("LMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift (Left).
        /// </summary>
        internal static string LShiftKey {
            get {
                return ResourceManager.GetString("LShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (Left).
        /// </summary>
        internal static string LWin {
            get {
                return ResourceManager.GetString("LWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        internal static string MediaNextTrack {
            get {
                return ResourceManager.GetString("MediaNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string MediaPlayPause {
            get {
                return ResourceManager.GetString("MediaPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        internal static string MediaPreviousTrack {
            get {
                return ResourceManager.GetString("MediaPreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string MediaStop {
            get {
                return ResourceManager.GetString("MediaStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad *.
        /// </summary>
        internal static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Down.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Lock.
        /// </summary>
        internal static string NumLock {
            get {
                return ResourceManager.GetString("NumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 0.
        /// </summary>
        internal static string NumPad0 {
            get {
                return ResourceManager.GetString("NumPad0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 1.
        /// </summary>
        internal static string NumPad1 {
            get {
                return ResourceManager.GetString("NumPad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 2.
        /// </summary>
        internal static string NumPad2 {
            get {
                return ResourceManager.GetString("NumPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 3.
        /// </summary>
        internal static string NumPad3 {
            get {
                return ResourceManager.GetString("NumPad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 4.
        /// </summary>
        internal static string NumPad4 {
            get {
                return ResourceManager.GetString("NumPad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 5.
        /// </summary>
        internal static string NumPad5 {
            get {
                return ResourceManager.GetString("NumPad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 6.
        /// </summary>
        internal static string NumPad6 {
            get {
                return ResourceManager.GetString("NumPad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 7.
        /// </summary>
        internal static string NumPad7 {
            get {
                return ResourceManager.GetString("NumPad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 8.
        /// </summary>
        internal static string NumPad8 {
            get {
                return ResourceManager.GetString("NumPad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad 9.
        /// </summary>
        internal static string NumPad9 {
            get {
                return ResourceManager.GetString("NumPad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string Oem1 {
            get {
                return ResourceManager.GetString("Oem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string Oem102 {
            get {
                return ResourceManager.GetString("Oem102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Oem2 {
            get {
                return ResourceManager.GetString("Oem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        internal static string Oem3 {
            get {
                return ResourceManager.GetString("Oem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string Oem4 {
            get {
                return ResourceManager.GetString("Oem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string Oem5 {
            get {
                return ResourceManager.GetString("Oem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string Oem6 {
            get {
                return ResourceManager.GetString("Oem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string Oem7 {
            get {
                return ResourceManager.GetString("Oem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string OemBackslash {
            get {
                return ResourceManager.GetString("OemBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string OemCloseBrackets {
            get {
                return ResourceManager.GetString("OemCloseBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Oemcomma {
            get {
                return ResourceManager.GetString("Oemcomma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string OemMinus {
            get {
                return ResourceManager.GetString("OemMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string OemOpenBrackets {
            get {
                return ResourceManager.GetString("OemOpenBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string OemPeriod {
            get {
                return ResourceManager.GetString("OemPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string OemPipe {
            get {
                return ResourceManager.GetString("OemPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string Oemplus {
            get {
                return ResourceManager.GetString("Oemplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string OemQuestion {
            get {
                return ResourceManager.GetString("OemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string OemQuotes {
            get {
                return ResourceManager.GetString("OemQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string OemSemicolon {
            get {
                return ResourceManager.GetString("OemSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        internal static string Oemtilde {
            get {
                return ResourceManager.GetString("Oemtilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Down.
        /// </summary>
        internal static string PageDown {
            get {
                return ResourceManager.GetString("PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Up.
        /// </summary>
        internal static string PageUp {
            get {
                return ResourceManager.GetString("PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Screen.
        /// </summary>
        internal static string PrintScreen {
            get {
                return ResourceManager.GetString("PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Up.
        /// </summary>
        internal static string Prior {
            get {
                return ResourceManager.GetString("Prior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        internal static string Q {
            get {
                return ResourceManager.GetString("Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control (Right).
        /// </summary>
        internal static string RControlKey {
            get {
                return ResourceManager.GetString("RControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arrow.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt (Right).
        /// </summary>
        internal static string RMenu {
            get {
                return ResourceManager.GetString("RMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift (Right).
        /// </summary>
        internal static string RShiftKey {
            get {
                return ResourceManager.GetString("RShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (Right).
        /// </summary>
        internal static string RWin {
            get {
                return ResourceManager.GetString("RWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Lock.
        /// </summary>
        internal static string Scroll {
            get {
                return ResourceManager.GetString("Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Media.
        /// </summary>
        internal static string SelectMedia {
            get {
                return ResourceManager.GetString("SelectMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string ShiftKey {
            get {
                return ResourceManager.GetString("ShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Screen.
        /// </summary>
        internal static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacebar.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad -.
        /// </summary>
        internal static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Arrow.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        internal static string VolumeDown {
            get {
                return ResourceManager.GetString("VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mute.
        /// </summary>
        internal static string VolumeMute {
            get {
                return ResourceManager.GetString("VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        internal static string VolumeUp {
            get {
                return ResourceManager.GetString("VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
